# This is a definition file for GitLab CI.

default:
  timeout: 360m

stages:
  - build
  - test
  - deploy

#######################################################################################################################
### Building stages.
#######################################################################################################################
# These stages test the Docker implementation scripts for installing and building all needed dependencies, building
# DICOMautomaton, testing the built binaries (within the compilation environment), and then building an AppImage.

# CI build on Debian oldstable.
# Notes: reduced (or missing) optimization, some components may be missing.
build_ci_debian_oldstable:
  stage: build
  tags: [dcma, docker, linux]
  needs: []
  image: "debian:oldstable"
  before_script:
    - "cp -R ./docker/builders/ci /scratch"
    - "cp -R . /dcma"
    - "./scripts/enable_swapfile.sh"
  script:
    - |
      ( ( while true ; do sleep 30 ; printf '\n\n' ; df -h ; printf '\n\n' ; cat /proc/meminfo | grep 'Mem\|Cache\|Swap' ; printf '\n\n' ; done ) &)
      ./docker/builders/ci/implementation_ci_debian_oldstable.sh
      ./integration_tests/Run.sh -v
      ./scripts/extract_system_appimage.sh
  artifacts:
    paths:
      - "AppDir"
      - "DICOMautomaton*AppImage"
    expire_in: 72 hours

# CI build on Arch Linux.
# Notes: reduced (or missing) optimization, some components may be missing.
build_ci_arch:
  stage: build
  tags: [dcma, docker, linux]
  needs: []
  image: "archlinux:latest"
  before_script:
    - "cp -R ./docker/builders/ci /scratch"
    - "cp -R . /dcma"
    - "./scripts/enable_swapfile.sh"
  script:
    - |
      ( ( while true ; do sleep 30 ; printf '\n\n' ; df -h ; printf '\n\n' ; cat /proc/meminfo | grep 'Mem\|Cache\|Swap' ; printf '\n\n' ; done ) &)
      ./docker/builders/ci/implementation_ci_arch.sh
      ./integration_tests/Run.sh -v
      ./scripts/extract_system_appimage.sh
  artifacts:
    paths:
      - "AppDir"
      - "DICOMautomaton*AppImage"
    expire_in: 72 hours

# Perform a cross-compile with MXE.
# Notes: reduced (or missing) optimization, some components may be missing.
cross_compile_mxe:
  stage: build
  tags: [dcma, docker, linux]
  needs: []
  image: "hdclark/dcma_build_base_mxe:latest"
  before_script:
    - "cp -R . /dcma"
    - "./scripts/enable_swapfile.sh"
  script:
    - |
      ( ( while true ; do sleep 30 ; printf '\n\n' ; df -h ; printf '\n\n' ; cat /proc/meminfo | grep 'Mem\|Cache\|Swap' ; printf '\n\n' ; done ) &)
      ./docker/builders/mxe/implementation_mxe.sh
      rsync -avP /out/ ./Windows/
      strip ./Windows/usr/bin/*exe
      strip ./Windows/usr/lib/*a
  artifacts:
    paths:
      - "Windows"
    expire_in: 72 hours

# CI build on MacOS.
# Notes: some components may be missing.
build_ci_macos:
  stage: build
  tags: [dcma, macos]
  needs: []
  variables:
    BID: "$CI_COMMIT_SHA"
  script:
    - |
      ( ( while true ; do sleep 30 ; printf '\n\n' ; df -h ; printf '\n\n' ; printf '\n\n' ; done ) &)
      ./docker/builders/macos/implementation_macos.sh "${BID}"_workroot "${BID}"_installroot
      ./scripts/gather_macos_dylibs.sh "${BID}"_installroot "${BID}"_artifacts
      #rm -rf "${BID}"_installroot
  artifacts:
    paths:
      - "${BID}_artifacts"
    expire_in: 72 hours

## Full Arch Linux build.
#build_arch:
#  stage: build
#  tags: [dcma]
#  needs: []
#  image: "archlinux:latest"
#  before_script:
#    - "cp -R ./docker/build_bases/arch /scratch_base"
#    - "cp -R ./docker/builders/arch /scratch"
#    - "cp -R . /dcma"
#  script:
#    - |
#      ( ( while true ; do sleep 30 ; printf '\n\n' ; df -h ; printf '\n\n' ; cat /proc/meminfo | grep 'Mem\|Cache\|Swap' ; printf '\n\n' ; done ) &)
#      "/scratch_base/implementation_arch.sh"
#      "/scratch/implementation_arch.sh"
##  artifacts:
##    paths:
##      - mybinary
##      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
##      # cache:
##      #   paths:
##      #     - "*.o"

#######################################################################################################################
### Testing stages.
#######################################################################################################################
# These stages test the use of AppImage build artifacts on pristine systems. They basically test portability of the
# AppImage distribution.

# Same-system testing.
test_ci_debian_oldstable_on_debian_oldstable:
  stage: test
  tags: [dcma, docker, linux]
  needs: ["build_ci_debian_oldstable"]
  image: "debian:oldstable"
  script:
    # Provide minimal system libraries.
    - "./scripts/install_AppImage_runtime_dependencies.sh"
    # Unpack the AppImage and overlay it in the containers root filesystem.
    - "chmod 777 DICOMautomaton*AppImage"
    - "./DICOMautomaton*AppImage --appimage-extract"
    - "rsync -a ./squashfs-root/usr/ /usr/"
    # Ensure it can be run and then run tests.
    - "ldd $(pwd)/squashfs-root/usr/bin/dicomautomaton_dispatcher || true"
    - "dicomautomaton_dispatcher -h"
    - "./integration_tests/Run.sh -v"
  artifacts:
    paths:
      - "dcma_integration_testing"
    expire_in: 72 hours

test_ci_arch_on_arch:
  stage: test
  tags: [dcma, docker, linux]
  needs: ["build_ci_arch"]
  image: "archlinux:latest"
  script:
    # Provide minimal system libraries.
    - "./scripts/install_AppImage_runtime_dependencies.sh"
    # Unpack the AppImage and overlay it in the containers root filesystem.
    - "chmod 777 DICOMautomaton*AppImage"
    - "./DICOMautomaton*AppImage --appimage-extract"
    - "rsync -a ./squashfs-root/usr/ /usr/"
    # Ensure it can be run and then run tests.
    - "ldd $(pwd)/squashfs-root/usr/bin/dicomautomaton_dispatcher || true"
    - "dicomautomaton_dispatcher -h"
    - "./integration_tests/Run.sh -v"
  artifacts:
    paths:
      - "dcma_integration_testing"
    expire_in: 72 hours

# Cross-system testing.
test_ci_debian_oldstable_on_arch:
  stage: test
  tags: [dcma, docker, linux]
  needs: ["build_ci_debian_oldstable"]
  image: "archlinux:latest"
  script:
    # Provide minimal system libraries.
    - "./scripts/install_AppImage_runtime_dependencies.sh"
    # Unpack the AppImage and overlay it in the containers root filesystem.
    - "chmod 777 DICOMautomaton*AppImage"
    - "./DICOMautomaton*AppImage --appimage-extract"
    - "rsync -a ./squashfs-root/usr/ /usr/"
    # Ensure it can be run and then run tests.
    - "ldd $(pwd)/squashfs-root/usr/bin/dicomautomaton_dispatcher || true"
    - "dicomautomaton_dispatcher -h"
    - "./integration_tests/Run.sh -v"
  artifacts:
    paths:
      - "dcma_integration_testing"
    expire_in: 72 hours

test_ci_debian_oldstable_on_ubuntu_latest:
  stage: test
  tags: [dcma, docker, linux]
  needs: ["build_ci_debian_oldstable"]
  image: "ubuntu:latest"
  script:
    # Provide minimal system libraries.
    - "./scripts/install_AppImage_runtime_dependencies.sh"
    # Unpack the AppImage and overlay it in the containers root filesystem.
    #- "wget --no-check-certificate 'http://halclark.ca/ci/DICOMautomaton-latest-x86_64.AppImage'"
    - "chmod 777 DICOMautomaton*AppImage"
    - "./DICOMautomaton*AppImage --appimage-extract"
    - "rsync -a ./squashfs-root/usr/ /usr/"
    # Ensure it can be run and then run tests.
    - "ldd $(pwd)/squashfs-root/usr/bin/dicomautomaton_dispatcher || true"
    - "dicomautomaton_dispatcher -h"
    #- git clone 'https://github.com/hdclark/DICOMautomaton'
    #- cd DICOMautomaton
    - "./integration_tests/Run.sh -v"
  artifacts:
    paths:
      - "dcma_integration_testing"
    expire_in: 72 hours

test_ci_debian_oldstable_on_fedora_latest:
  stage: test
  tags: [dcma, docker, linux]
  needs: ["build_ci_debian_oldstable"]
  image: "fedora:latest"
  script:
    # Provide minimal system libraries.
    - "./scripts/install_AppImage_runtime_dependencies.sh"
    # Unpack the AppImage and overlay it in the containers root filesystem.
    #- "wget --no-check-certificate 'http://halclark.ca/ci/DICOMautomaton-latest-x86_64.AppImage'"
    - "chmod 777 DICOMautomaton*AppImage"
    - "./DICOMautomaton*AppImage --appimage-extract"
    # Explicitly preload libraries using a wrapper.
    - |
      printf '%s\n' '#!/usr/bin/env bash' >> /usr/bin/dicomautomaton_dispatcher
      #printf '%s $@\n' "LD_LIBRARY_PATH=$(pwd)/squashfs-root/usr/lib $(pwd)/squashfs-root/usr/bin/dicomautomaton_dispatcher" >> /usr/bin/dicomautomaton_dispatcher
      printf '%s "$@"\n' "/usr/lib64/ld-linux-x86-64.so.2 --library-path $(pwd)/squashfs-root/usr/lib $(pwd)/squashfs-root/usr/bin/dicomautomaton_dispatcher" >> /usr/bin/dicomautomaton_dispatcher
      chmod 777 /usr/bin/dicomautomaton_dispatcher
    # Ensure it can be run and then run tests.
    - "ldd $(pwd)/squashfs-root/usr/bin/dicomautomaton_dispatcher || true"
    - "dicomautomaton_dispatcher -h"
    #- "git clone 'https://github.com/hdclark/DICOMautomaton'"
    #- "cd DICOMautomaton"
    - "./integration_tests/Run.sh -v"
  artifacts:
    paths:
      - "dcma_integration_testing"
    expire_in: 72 hours

# Cross-compilation testing.
test_cross_compile_mxe_on_debian_oldstable:
  stage: test
  tags: [dcma, docker, linux]
  needs: ["cross_compile_mxe"]
  image: "debian:oldstable"
  script:
    # Provide minimal system libraries.
    - "export DEBIAN_FRONTEND='noninteractive'"
    - "apt-get update --yes"
    - "apt-get install --yes --no-install-recommends git ca-certificates rsync mesa-utils"
    - "dpkg --add-architecture i386"
    - "apt-get update --yes"
    - "apt-get install --yes wine32 wine64"
    # Debugging note: to download the latest sources and Windows CI binaries:
    #- "apt-get install --yes wget unzip vim"
    #- "git clone https://github.com/hdclark/DICOMautomaton && cd DICOMautomaton"
    #- "wget 'https://gitlab.com/hdeanclark/DICOMautomaton/builds/artifacts/master/download?job=cross_compile_mxe' -O dcma.zip"
    #- "unzip dcma.zip"
    # Wrap the Windows binary with wine calls so it is transparent to the caller.
    - "chmod 777 Windows/usr/bin/*"
    - "rsync -a ./Windows/usr/ /usr/"
    - "echo '#!/bin/bash' > /usr/bin/dicomautomaton_dispatcher"
    - "echo 'exec wine /usr/bin/dicomautomaton_dispatcher.exe \"$@\"' >> /usr/bin/dicomautomaton_dispatcher"
    - "chmod 777 /usr/bin/dicomautomaton_dispatcher"
    # Ensure it can be run and then run tests.
    - "dicomautomaton_dispatcher -h"
    - "./integration_tests/Run.sh -v"
  artifacts:
    paths:
      - "dcma_integration_testing"
    expire_in: 72 hours

#######################################################################################################################
### Deployment stages.
#######################################################################################################################

deploy_ci_debian_oldstable:
  stage: deploy
  tags: [dcma, docker, linux]
  needs: ["test_ci_debian_oldstable_on_debian_oldstable"]
  script:
    - "echo 'Deployment placeholder successful'"
